Add all code from private repository
indykite/opa-indykite-plugin pull request #1
Opened 2022-09-20 12:05 UTC by arxeiss

This is copy from SDK folder. Performed changes:
- Changed Go module name to reflect repository name
- Added more linter rules

This is just to add all code to repo. Further refactoring and publishing will be done in future sprints.

2022-09-21 06:39 UTC, bakkelim commented on README.md
> + docker container run -it  indykite/indy-agent:latest version
should this be `indykite/opa:latest`?
Atleast that's what's it called in `.github/workflows/build-and-publish.yaml` and in dockerhub (public repo)

2022-09-21 06:39 UTC, bakkelim commented on cmd/root.go
> +}
are we using this file?

2022-09-21 06:39 UTC, bakkelim commented on config.yaml
> +        key: <PEM_encoded_public_key>
is this entire file okay, in regards to this repo being public?

2022-09-21 06:39 UTC, bakkelim commented on main.go
> +		fmt.Println(err)
is this command needed to initialize plugins?

2022-09-21 07:21 UTC, marvinkite requested changes
Looks good, there are some clean up comments.

2022-09-21 07:21 UTC, marvinkite commented on functions/client.go
> +// Copyright (c) 2020 IndyKite
Let's update all date to 2022

2022-09-21 07:21 UTC, marvinkite commented on functions/client.go
> +
Let's document all public functions. This is a function others can use to create new functions and extend the plugin.

2022-09-21 07:21 UTC, marvinkite commented on functions/identity.go
> +			// return ast.ObjectTerm(k), nil
If not used let's remove the dead code.

2022-09-21 07:21 UTC, marvinkite commented on main.go
> +	// For GCP log.SetFormatter(joonix.NewFormatter())
Let's remove these comments.

2022-09-21 07:21 UTC, marvinkite commented on plugins/identity.go
> +		//	api.WithCredentialsLoader(api.StaticCredentialConfig(p.config.credConfig)),
Let's remove this comment

2022-09-21 07:23 UTC, arxeiss commented on README.md
> + docker container run -it  indykite/indy-agent:latest version
Yes, fixed

2022-09-21 08:05 UTC, maaland reviewed
I agree with the others' comments.

2022-09-21 08:05 UTC, maaland commented on utilities/conversion.go
> +	// 	a := pv.DurationValue.
remove comment

2022-09-21 08:14 UTC, arxeiss commented on main.go
> +		fmt.Println(err)
Yep, required

2022-09-21 08:14 UTC, arxeiss commented on config.yaml
> +        key: <PEM_encoded_public_key>
No, will clean up

2022-09-21 08:15 UTC, arxeiss commented on README.md
> + docker container run -it  indykite/indy-agent:latest version
Sure, fixed to `indykite/opa`

2022-09-21 09:24 UTC, arxeiss commented on functions/client.go
> +
Fixed and added linter to force this

2022-09-21 09:32 UTC, arxeiss commented on functions/client.go
> +// Copyright (c) 2020 IndyKite
Done and force with linter too

2022-09-21 09:32 UTC, arxeiss commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] commit message follows [commit guidelines](https://github.com/indykite/jarvis-sdk-go/blob/master/doc/guides/commit-message.md)
Fixed and create PR with updated file in organization level repo

2022-09-21 10:42 UTC, maaland approved these changes

2022-09-23 06:58 UTC, marvinkite approved these changes

2022-09-23 07:01 UTC, merged